### ISSUE TITLE
Does not handle jobs which specify number of max simultaneous tasks

### ISSUE THREAD

**Issue by prehensilecode** [marklisi1/seff-array#15]
It is possible to specify the max number of simultaneously running tasks by, e.g.
```
   --array=1-10000%500
```

This results in `sacct` output which may look like:
```
123456_[9201-10000%500]|jobname||00:00:00|3Gn|1|05:00:00|PENDING|00:00:00|user1|user1|foocluster|0:0
```

Running `seff-array.py` on that gives the error message:
```
Traceback (most recent call last):
  File "//opt/seff-array/bin/seff-array.py", line 698, in <module>
    main(args.jobid, args.m, args.t, args.c)
  File "/opt/seff-array/bin/seff-array.py", line 506, in main
    end = int(end[:-1])
ValueError: invalid literal for int() with base 10: '10000%500'
```

**Comment by tlangfor** [comment]
Thanks for catching this. It's been merged and I'm closing the issue.
