### ISSUE TITLE
Sanitize User Input

### ISSUE THREAD

**Issue by ifelsefi** [marklisi1/seff-array#18]
This is a great script though if ran against a non-array job it fails so would be useful to exit the script with an exception if that was attempted.  For example:

```
me@server[~/repos/seff-array]$ sacct -p -j 41305312 --format=JobID,JobName,MaxRSS,Elapsed,ReqMem,ReqCPUS,Timelimit
JobID|JobName|MaxRSS|Elapsed|ReqMem|ReqCPUS|Timelimit|
41305312|allocation||00:00:00|0n|0||
41305312.foo|9228K|00:10:42|0n|5||
41305312.bar|bar|1612K|00:10:42|0n|5||
41305312.0|thejob|47686692K|00:10:39|0n|5||
```

When I run:

```
me@server[~/repos/seff-array]$ ./seff-array.py 41305312
Traceback (most recent call last):
  File "./seff-array.py", line 699, in <module>
    main(args.jobid, args.m, args.t, args.c)
  File "./seff-array.py", line 551, in main
    cpuTime_sum += cpuTime / num_req_cpus
ZeroDivisionError: float division by zero
```

Could that be added?

**Comment by tlangfor** [comment]
The error is complaining that when it attempts to calculate the CPU Time it's dividing by `num_req_cpus` which in your `sacct` output is `0`, so it's throwing a `ZeroDivisionError`. 

On our system a non-array job looks like this:

```sh
[me@server ~]$ sacct -p -j 36324498 --format=JobID,JobName,MaxRSS,Elapsed,ReqMem,ReqCPUS,TimeLimit
JobID|JobName|MaxRSS|Elapsed|ReqMem|ReqCPUS|Timelimit|
36324498|bash||00:25:56|5Gc|2|01:00:00|
36324498.extern|extern||00:25:56|5Gc|2||
36324498.0|bash|4484K|00:25:56|5Gc|2||
```

```sh
[me@server ~]$ seff-array 36324498
Job ID: 36324498
Cluster: server
User/Group: me/support
State: COMPLETED (exit code 0)
Cores: 2
Average CPU Utilized: 00:00.20
CPU Efficiency: 0.01% of 25:56 core-walltime
Job Wall-clock time: 25:56
Average Memory Utilized: 4.48MB
Memory Efficiency: 0.04% of 10.0GB
Memory Usage: 4.48MB
Requested Memory: 5.0GB
This job used 0.18% of its requested memory.
Consider requesting less memory to decrease waittime.

Elapsed Time: 00:25:56
Requested Time: 01:00:00
This job used 43.22% of its requested time.

Cores Requested: 2
CPU efficiency for this job is 0.01%.
Consider requesting less cores to decrease waittime.
```

I'm curious why your `sacct` is reporting 0CPUs for the top line. What version of Slurm are you running?

**Comment by ifelsefi** [comment]
Old.

`slurm 18.08.4`

I will close.
